// ─── Chemical Database & Local Fallback Reactions ─────────────
export const CHEMICALS = [
    { id: 'hcl', name: 'Hydrochloric Acid (HCl)', formula: 'HCl' },
    { id: 'naoh', name: 'Sodium Hydroxide (NaOH)', formula: 'NaOH' },
    { id: 'h2so4', name: 'Sulfuric Acid (H₂SO₄)', formula: 'H₂SO₄' },
    { id: 'na', name: 'Sodium Metal (Na)', formula: 'Na' },
    { id: 'h2o', name: 'Water (H₂O)', formula: 'H₂O' },
    { id: 'nahco3', name: 'Baking Soda (NaHCO₃)', formula: 'NaHCO₃' },
    { id: 'ch3cooh', name: 'Vinegar (CH₃COOH)', formula: 'CH₃COOH' },
    { id: 'h2o2', name: 'Hydrogen Peroxide (H₂O₂)', formula: 'H₂O₂' },
    { id: 'kno3', name: 'Potassium Nitrate (KNO₃)', formula: 'KNO₃' },
    { id: 'agno3', name: 'Silver Nitrate (AgNO₃)', formula: 'AgNO₃' },
    { id: 'nacl', name: 'Sodium Chloride (NaCl)', formula: 'NaCl' },
    { id: 'fe', name: 'Iron Filings (Fe)', formula: 'Fe' },
    { id: 'cuso4', name: 'Copper Sulfate (CuSO₄)', formula: 'CuSO₄' },
    { id: 'mg', name: 'Magnesium Ribbon (Mg)', formula: 'Mg' },
    { id: 'zn', name: 'Zinc Metal (Zn)', formula: 'Zn' },
];

function k(a, b) { return [a, b].sort().join('+'); }

export const REACTIONS = {
    [k('hcl', 'naoh')]: { risk: 'safe', effect: 'green_glow', message: 'Neutralization produces salt and water.', explanation: '✅ <strong>Safe Reaction</strong><br><br><strong>HCl + NaOH → NaCl + H₂O</strong><br><br>This is a <em>Neutralization</em> reaction. Classic acid-base neutralization producing table salt and water.<br><br><strong>Product:</strong> Sodium Chloride + Water', teacher_notes: 'Strong acid + strong base. pH at equivalence = 7. ΔH ≈ −57.3 kJ/mol. Great titration example.', equation: 'HCl + NaOH → NaCl + H₂O', product: 'Sodium Chloride + Water', type: 'Neutralization' },
    [k('hcl', 'nahco3')]: { risk: 'safe', effect: 'green_glow', message: 'Produces CO₂ gas bubbles.', explanation: '✅ <strong>Safe Reaction</strong><br><br><strong>HCl + NaHCO₃ → NaCl + H₂O + CO₂↑</strong><br><br>This is an <em>Acid-Carbonate</em> reaction producing effervescent CO₂ gas bubbles.<br><br><strong>Product:</strong> Salt + Water + Carbon Dioxide', teacher_notes: 'CO₂ tested with limewater (turns milky). Great for teaching gas collection.', equation: 'HCl + NaHCO₃ → NaCl + H₂O + CO₂↑', product: 'Salt + Water + CO₂', type: 'Acid-Carbonate' },
    [k('ch3cooh', 'nahco3')]: { risk: 'safe', effect: 'green_glow', message: 'Vigorous fizzing — vinegar + baking soda!', explanation: '✅ <strong>Safe Reaction</strong><br><br><strong>CH₃COOH + NaHCO₃ → CH₃COONa + H₂O + CO₂↑</strong><br><br>The famous vinegar & baking soda reaction with vigorous fizzing!<br><br><strong>Product:</strong> Sodium Acetate + Water + CO₂', teacher_notes: 'Sodium acetate can make "hot ice" demos. Reaction is endothermic.', equation: 'CH₃COOH + NaHCO₃ → CH₃COONa + H₂O + CO₂↑', product: 'Sodium Acetate + Water + CO₂', type: 'Acid-Carbonate' },
    [k('na', 'h2o')]: { risk: 'danger', effect: 'explosion', message: '⚠️ EXTREMELY exothermic! May ignite or explode.', explanation: '🔴 <strong>DANGER — High Risk!</strong><br><br><strong>2Na + 2H₂O → 2NaOH + H₂↑</strong><br><br>This <em>Single Displacement</em> reaction is extremely dangerous! Sodium reacts violently with water, may ignite or explode.<br><br><strong>Product:</strong> Sodium Hydroxide + Hydrogen Gas<br><strong>Safety:</strong> DO NOT attempt outside a professional lab. Full PPE required.', teacher_notes: 'Alkali metals increase in reactivity down Group 1. Never use pieces larger than a pea. H₂ is flammable.', equation: '2Na + 2H₂O → 2NaOH + H₂↑', product: 'NaOH + Hydrogen Gas', type: 'Single Displacement' },
    [k('h2so4', 'na')]: { risk: 'danger', effect: 'explosion', message: '⚠️ Extremely dangerous! Violent exothermic reaction.', explanation: '🔴 <strong>DANGER — High Risk!</strong><br><br><strong>2Na + H₂SO₄ → Na₂SO₄ + H₂↑</strong><br><br>This <em>Single Displacement</em> is even more dangerous than Na + water.<br><br><strong>Product:</strong> Sodium Sulfate + Hydrogen Gas<br><strong>Safety:</strong> Never attempt in school lab. Simulation only.', teacher_notes: 'Concentrated acid adds thermal energy. Use simulation only.', equation: '2Na + H₂SO₄ → Na₂SO₄ + H₂↑', product: 'Na₂SO₄ + H₂', type: 'Single Displacement' },
    [k('h2so4', 'naoh')]: { risk: 'moderate', effect: 'smoke', message: 'Highly exothermic neutralization.', explanation: '⚠️ <strong>Moderate Risk</strong><br><br><strong>H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O</strong><br><br>This <em>Neutralization</em> requires caution. Significant heat released.<br><br><strong>Product:</strong> Sodium Sulfate + Water<br><strong>Safety:</strong> Wear goggles and gloves. Always add acid to base.', teacher_notes: 'Diprotic acid + strong base. 2:1 mole ratio. Always add acid to base, never reverse.', equation: 'H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O', product: 'Na₂SO₄ + Water', type: 'Neutralization' },
    [k('agno3', 'nacl')]: { risk: 'safe', effect: 'green_glow', message: 'White curdy precipitate of AgCl.', explanation: '✅ <strong>Safe Reaction</strong><br><br><strong>AgNO₃ + NaCl → AgCl↓ + NaNO₃</strong><br><br>Classic <em>Double Displacement</em> precipitation test.<br><br><strong>Product:</strong> Silver Chloride + Sodium Nitrate', teacher_notes: 'AgCl is photosensitive — basis of photography. AgNO₃ stains skin.', equation: 'AgNO₃ + NaCl → AgCl↓ + NaNO₃', product: 'AgCl + NaNO₃', type: 'Double Displacement' },
    [k('fe', 'cuso4')]: { risk: 'safe', effect: 'green_glow', message: 'Iron displaces copper; solution turns green.', explanation: '✅ <strong>Safe Reaction</strong><br><br><strong>Fe + CuSO₄ → FeSO₄ + Cu</strong><br><br><em>Single Displacement</em> — iron is more reactive than copper.<br><br><strong>Product:</strong> Iron(II) Sulfate + Copper', teacher_notes: 'Demonstrates reactivity series. Brown/red copper coats the iron nail. ~30 min for visible results.', equation: 'Fe + CuSO₄ → FeSO₄ + Cu', product: 'FeSO₄ + Cu', type: 'Single Displacement' },
    [k('mg', 'hcl')]: { risk: 'moderate', effect: 'smoke', message: 'Vigorous reaction producing hydrogen gas.', explanation: '⚠️ <strong>Moderate Risk</strong><br><br><strong>Mg + 2HCl → MgCl₂ + H₂↑</strong><br><br>This <em>Single Displacement</em> requires caution. Vigorous reaction producing flammable hydrogen gas.<br><br><strong>Product:</strong> MgCl₂ + H₂<br><strong>Safety:</strong> Use dilute acid, wear goggles.', teacher_notes: 'Great for rate-of-reaction experiments. Vary temperature/concentration/surface area. "Squeaky pop" test for H₂.', equation: 'Mg + 2HCl → MgCl₂ + H₂↑', product: 'MgCl₂ + H₂', type: 'Single Displacement' },
    [k('zn', 'hcl')]: { risk: 'moderate', effect: 'smoke', message: 'Moderate reaction speed with H₂ evolution.', explanation: '⚠️ <strong>Moderate Risk</strong><br><br><strong>Zn + 2HCl → ZnCl₂ + H₂↑</strong><br><br><em>Single Displacement</em> — zinc reacts more slowly than magnesium.<br><br><strong>Product:</strong> ZnCl₂ + H₂<br><strong>Safety:</strong> Wear goggles and gloves.', teacher_notes: 'Slower than Mg+HCl — illustrates reactivity trends. Add CuSO₄ as catalyst to speed up.', equation: 'Zn + 2HCl → ZnCl₂ + H₂↑', product: 'ZnCl₂ + H₂', type: 'Single Displacement' },
    [k('zn', 'cuso4')]: { risk: 'safe', effect: 'green_glow', message: 'Zinc displaces copper. Solution decolorizes.', explanation: '✅ <strong>Safe Reaction</strong><br><br><strong>Zn + CuSO₄ → ZnSO₄ + Cu</strong><br><br><em>Single Displacement</em> — zinc is above copper in reactivity series.<br><br><strong>Product:</strong> ZnSO₄ + Cu', teacher_notes: 'Compare with Fe + CuSO₄ to teach electrochemistry basics.', equation: 'Zn + CuSO₄ → ZnSO₄ + Cu', product: 'ZnSO₄ + Cu', type: 'Single Displacement' },
    [k('h2o2', 'kno3')]: { risk: 'moderate', effect: 'smoke', message: 'Catalyzed decomposition producing oxygen.', explanation: '⚠️ <strong>Moderate Risk</strong><br><br><strong>2H₂O₂ →(KNO₃)→ 2H₂O + O₂↑</strong><br><br>KNO₃ catalyzes decomposition of hydrogen peroxide. Keep away from flames.<br><br><strong>Product:</strong> Water + Oxygen Gas', teacher_notes: 'Test O₂ with glowing splint (relights). Compare with MnO₂ catalyst.', equation: '2H₂O₂ → 2H₂O + O₂↑', product: 'H₂O + O₂', type: 'Decomposition' },
    [k('mg', 'h2o')]: { risk: 'moderate', effect: 'smoke', message: 'Slow at room temp; reacts well with steam.', explanation: '⚠️ <strong>Moderate Risk</strong><br><br><strong>Mg + 2H₂O → Mg(OH)₂ + H₂↑</strong><br><br><em>Single Displacement</em> — very slow with cold water, vigorous with steam.<br><br><strong>Product:</strong> Mg(OH)₂ + H₂', teacher_notes: 'Useful for comparing Group 2 reactivity. Mg(OH)₂ is "milk of magnesia" — an antacid.', equation: 'Mg + 2H₂O → Mg(OH)₂ + H₂↑', product: 'Mg(OH)₂ + H₂', type: 'Single Displacement' },
    [k('h2so4', 'zn')]: { risk: 'moderate', effect: 'smoke', message: 'Steady H₂ evolution. Use dilute acid only.', explanation: '⚠️ <strong>Moderate Risk</strong><br><br><strong>Zn + H₂SO₄ → ZnSO₄ + H₂↑</strong><br><br><em>Single Displacement</em> with dilute sulfuric acid.<br><br><strong>Product:</strong> ZnSO₄ + H₂<br><strong>Safety:</strong> Concentrated H₂SO₄ produces SO₂ instead!', teacher_notes: 'Only works with dilute H₂SO₄. Concentrated H₂SO₄ produces SO₂ — important A-level distinction.', equation: 'Zn + H₂SO₄ → ZnSO₄ + H₂↑', product: 'ZnSO₄ + H₂', type: 'Single Displacement' },
};

export const QA = [
    { keywords: ['hello', 'hi', 'hey'], reply: 'Hello! 👋 I\'m your lab assistant. Select two chemicals and press Mix, or ask me a chemistry question!' },
    { keywords: ['neutralization', 'neutralisation'], reply: '🧪 <strong>Neutralization</strong> is a reaction between an acid and a base forming salt and water. Example: HCl + NaOH → NaCl + H₂O' },
    { keywords: ['exothermic'], reply: '🔥 <strong>Exothermic</strong> reactions release heat. Temperature increases. Examples: combustion, neutralization.' },
    { keywords: ['endothermic'], reply: '❄️ <strong>Endothermic</strong> reactions absorb heat. Temperature decreases. Example: photosynthesis, dissolving ammonium nitrate.' },
    { keywords: ['acid', 'base', 'ph'], reply: '⚗️ <strong>Acids</strong> have pH < 7, <strong>bases</strong> have pH > 7. Strong acids fully dissociate; weak acids partially dissociate.' },
    { keywords: ['safety', 'ppe', 'goggles'], reply: '🥽 Always wear safety goggles, lab coat, and gloves. Know the location of eyewash stations and fire extinguishers.' },
    { keywords: ['reactivity', 'series'], reply: '📊 <strong>Reactivity Series</strong>: K > Na > Ca > Mg > Al > Zn > Fe > Cu > Ag > Au. More reactive metals displace less reactive ones.' },
    { keywords: ['displacement'], reply: '🔄 <strong>Displacement</strong> reactions occur when a more reactive element replaces a less reactive one from a compound.' },
    { keywords: ['precipit'], reply: '🧫 A <strong>precipitation</strong> reaction forms an insoluble solid when two solutions are mixed. E.g., AgNO₃ + NaCl → AgCl↓' },
    { keywords: ['catalyst'], reply: '⚡ A <strong>catalyst</strong> speeds up a reaction without being consumed. It lowers the activation energy.' },
    { keywords: ['help', 'what can you do'], reply: '🤖 I can explain reactions, answer chemistry questions, and provide safety guidance. Try mixing chemicals or ask about acids, reactivity series, or safety!' },
];

export function reactionKey(a, b) { return [a, b].sort().join('+'); }
